---
- name: Ensure SSH daemon is running.
  service:
    name: ssh
    state: started

- name: Update SSH configuration to be more secure.
  template:
    src: sshd_config.j2
    dest: /etc/ssh/sshd_config
    validate: "sshd -T -f %s"
    mode: 0644
  notify:
    - restart_ssh

- name: Flush handlers.
  meta: flush_handlers
